version: '3'

services:
  api:
    container_name: ${DB_DATABASE}-api-${DB_NAME}
    restart: unless-stopped
    build: 
      dockerfile: ./dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
    depends_on: 
      - db
  db: 
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    image: mysql:5.6
    container_name: ${DB_DATABASE}-mysql-${DB_NAME}
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  adminer:
    image: adminer
    container_name: ${DB_DATABASE}-adminer-${DB_NAME}
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 8080:8080